# Generated by Django 3.1.1 on 2020-12-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('winner_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('form_01', models.CharField(max_length=400)),
                ('form_02', models.CharField(max_length=400)),
                ('form_03', models.CharField(max_length=400)),
                ('form_04', models.CharField(max_length=400)),
                ('form_05', models.CharField(max_length=400)),
                ('form_06', models.CharField(max_length=400)),
                ('form_07', models.CharField(max_length=400)),
                ('form_08', models.CharField(max_length=400)),
                ('form_09', models.CharField(max_length=400)),
                ('form_10', models.CharField(max_length=400)),
                ('form_11', models.CharField(max_length=400)),
                ('form_12', models.CharField(max_length=400)),
                ('form_13', models.CharField(max_length=400)),
            ],
        ),
    ]
